#include <exception>

#include "../ex.h"

void func() {
    try {

    } catch(std::exception &ex) {
    }
}